name: Build and Deploy Spring Boot

on:
  push:
    branches:
      - master  # Change to your default branch if it's different
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use 'temurin' for OpenJDK, 'oracle' for Oracle JDK
          java-version: '22'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload Artifact (JAR file)
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/Basic_CRUD_Oprations-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: target/

      - name: Deploy to Server via SCP
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem target/Basic_CRUD_Oprations-0.0.1-SNAPSHOT.jar.jar $USER@$HOST:/home/ubuntu/CFC_Backend/target/Basic_CRUD_Oprations-0.0.1-SNAPSHOT.jar
          ssh -i private_key.pem $USER@$HOST "sudo systemctl restart my-spring-app"

