name: Build and Deploy Spring Boot

on:
  workflow_dispatch:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build Application
        run: mvn clean package -DskipTests

      - name: Verify Generated Files
        run: |
          echo "==== TARGET DIRECTORY ===="
          ls -la target

          echo "==== VERIFY APPLICATION PROPERTIES INSIDE JAR ===="
          jar xf target/cfc-platform-0.0.1-SNAPSHOT.jar BOOT-INF/classes/application.properties

          cat BOOT-INF/classes/application.properties

      - name: Upload Spring Boot JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/cfc-platform-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: CFC_Backend

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: target/

      - name: Verify Downloaded Artifact
        run: |
          echo "==== DOWNLOADED FILES ===="
          ls -la target

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ubuntu

        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          echo "==== CLEAN OLD FILES ON EC2 ===="

          ssh -i private_key.pem \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          $USER@$HOST "
            rm -f /home/ubuntu/CFC_Backend/target/*.jar.original
          "

          echo "==== COPY NEW JAR ===="

          scp -i private_key.pem \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          target/cfc-platform-0.0.1-SNAPSHOT.jar \
          $USER@$HOST:/home/ubuntu/CFC_Backend/target/

          echo "==== RESTART APPLICATION ===="

          ssh -i private_key.pem \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          $USER@$HOST "
            sudo systemctl restart my-spring-app
            sleep 10
            sudo systemctl status my-spring-app --no-pager
          "
